[versions]
compose-bom = "2025.04.00"
firebase-bom = "33.14.0"
hilt = "2.56.2"
kotlin = "2.1.21"
ktlint = "0.50.0"
paparazzi = "1.3.5"

[plugins]
spotless = { id = "com.diffplug.spotless", version = "7.0.4" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }

[libraries]
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-material-material = "androidx.compose.material:material:1.8.2"
androidx-compose-material3-material3 = "androidx.compose.material3:material3:1.3.2"
androidx-compose-material-material-icons-extended = "androidx.compose.material:material-icons-extended:1.7.8"
androidx-compose-ui-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-ui-text = { group = "androidx.compose.ui", name = "ui-text-google-fonts" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-constraintlayout-compose = "androidx.constraintlayout:constraintlayout-compose:1.1.1"
androidx-core = "androidx.core:core-ktx:1.16.0"
androidx-hilt-navigation-compose = "androidx.hilt:hilt-navigation-compose:1.2.0"
androidx-lifecycle-runtime = "androidx.lifecycle:lifecycle-runtime-ktx:2.9.0"
androidx-lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.9.0"
androidx-navigation-compose = "androidx.navigation:navigation-compose:2.9.0"
coil-compose = "io.coil-kt:coil-compose:2.7.0"
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-config = { group = "com.google.firebase", name = "firebase-config-ktx" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging-ktx" }
hilt-library = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
kotlin-coroutines-play-services = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.10.2"
material3 = "com.google.android.material:material:1.12.0"
protobuf-javalite = "com.google.protobuf:protobuf-javalite:4.31.1"
protobuf-protoc = "com.google.protobuf:protoc:4.31.1"

androidx-test-junit = "androidx.test.ext:junit:1.2.1"
androidx-test-espresso-core = "androidx.test.espresso:espresso-core:3.6.1"
junit = "junit:junit:4.13.2"

android-plugin-gradle = "com.android.tools.build:gradle:8.10.1"
google-services = "com.google.gms:google-services:4.4.2"
kotlin-plugin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
hilt-plugin-gradle = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
paparazzi-plugin-gradle = { module = "app.cash.paparazzi:paparazzi-gradle-plugin", version.ref = "paparazzi" }